###
# Find All avatar
GET  http://localhost:3000/avatar

###
# Find avatar By Id
GET  http://localhost:3000/avatar/1

###
# Create avatar
POST  http://localhost:3000/avatar
Content-Type: application/json

{
    "email": "example@email.com",
    "name": "username",
    "password": "password"
}

###
# Delete avatar By Id
DELETE  http://localhost:3000/avatar/6321f97f0fda161d5cc3b748
